### ISSUE TITLE
Does not work on linux using node >= 7

### ISSUE THREAD

**Issue by jeroenvollenbrock** [evanlucas/reset-date-cache#2]
The module does not work in node v8.9, the timezone does not get modified.

**Comment by evanlucas** [comment]
Hi, @jeroenvollenbrock. Thanks for opening an issue. Do you have a reproducible test case that shows this? Also, what platform and exact node version are you running?

**Comment by jeroenvollenbrock** [comment]
The test.js in the repository fails to run on the latest debian stretch using NodeJS 8.9.4

**Comment by jeroenvollenbrock** [comment]
Hi @evanlucas, Do you happen to have any update on this issue?

**Comment by evanlucas** [comment]
I'm honestly not sure what the problem is here. I can reproduce on debian jessie as well. Isn't an issue on macOS though.

**Comment by evanlucas** [comment]
Hi, can you try v1.0.4? That should fix the issue we have been seeing. I just confirmed it works on Debian Jessie. Thanks!

**Comment by jeroenvollenbrock** [comment]
Seems to work, Awesome! 😄 
Feeling kinda stupid for failing to recognize the need for the additional tzset call 🙈

Given the conversation in the node issue and the discussion in the PR, i'm thinking of writing a seperate module that listens for the different platform timezone events and invoke the timezone change notification when it receives a trigger. I've already written one to use the DBus [systemd](https://github.com/nodejs/node/pull/20026#issuecomment-381318983) api to do this for my specific use-case, but i guess a simple inotify on the timezone config files might result in a more compatible setup. It bugs me a bit that there is no currently available way to correctly handle these changes, especially with more and more electron-like and daemon-style node applications coming up.
